# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

SENDGRID_PASSWORD: sz0dabog8515
#hlbvxcbu 
SENDGRID_USERNAME: app35275271@heroku.com
AWS_ACCESS_KEY_ID: AKIAI7WSQP6SXYS2XKEA
AWS_SECRET_ACCESS_KEY: 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
development:
  AWS_BUCKET: vmanamino-bloccit-development
production:
  AWS_BUCKET: vmanamino-bloccit-production

development:
  secret_key_base: b531639e8d776ea53317cd74f02706b885738e33ddf4810877b264b8d226943f72fd248f40c96e2026455f79a44253a972cdb09e563ef32c40a3feca90a32288

test:
  secret_key_base: d5c2946b75743ceabb81f3c76fc38e56763fe5e6e94acca7c4cdcb0a0472b7cd25f2d96f2c100c39aa3e447eaaeb936344920a180dcd9ce32ca5e84b59fcf797